<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>CommerceEdge.Application.Tests</AssemblyName>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\CommerceEdge.Application\CommerceEdge.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" Version="4.0.1" />
    <PackageReference Include="FluentAssertions" Version="8.*" />
    <PackageReference Include="NSubstitute" Version="6.2.0" />
  </ItemGroup>
</Project>
