<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AssemblyName>CommerceEdge.Api</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CommerceEdge.Observability.AspNetCore\CommerceEdge.Observability.AspNetCore.csproj" />
    <ProjectReference Include="..\CommerceEdge.Application\CommerceEdge.Application.csproj" />
    <ProjectReference Include="..\CommerceEdge.Infrastructure\CommerceEdge.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="CommerceEdge.Api.IntegrationTests" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.*" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.*" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.*" />
  </ItemGroup>
</Project>
