name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  backend:
    uses: ./.github/workflows/backend.yml

  web:
    uses: ./.github/workflows/web.yml

  pos:
    uses: ./.github/workflows/pos.yml
